version: "3.9"

services:
  postgres:
    image: postgres:14
    environment:
      - POSTGRES_DB=bookshelf
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d bookshelf"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    restart: always
    environment:
      - PROJECT_MODE=DEVELOPMENT
      - HTTP_PORT=3000
      - HTTP_HOST=0.0.0.0
      - PSQL_URI=postgresql://postgres:postgres@postgres:5432/bookshelf?sslmode=disable
    ports:
      - "18000:3000"
